server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
#-- my sql --
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bootcamp
#    username: root
#    password: root
#-- postgre --
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp
    username: postgres
    password: 123456
  jpa:
#    database-platform=org: hibernate.dialect.MySQL5InnoDBDialect
    database-platform=org: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

application:
  description: Projeto criado para o bootcamp DIO - Santander
  version: 1.0